version: 2
updates:
  # GitHub Actions security
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # NPM packages (Next.js, React, etc.)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
