name: "Security vulnerability"
description: "Report a security bug in iobeats-player"
labels: ["security", "investigate"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ Please use private reporting when possible (Security tab → Report a vulnerability).
        If you continue here, do NOT share secrets or sensitive data.
  - type: input
    id: impact
    attributes:
      label: What’s the impact?
      placeholder: ex. XSS in audio player, leakage of API keys
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: 1. Go to … 2. Click … 3. Observe …
  - type: textarea
    id: notes
    attributes:
      label: Extra notes / context
