name: Update changelog (manual)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag version (e.g. v2.0.73)'
        required: true
        type: string

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Debug inputs
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Input tag: ${{ inputs.tag }}"

      - name: Update CHANGELOG.md
        env:
          TAG: ${{ inputs.tag }}   # <- on passe le tag au script ici
        run: node scripts/update-changelog.mjs

      - name: Commit & push
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add CHANGELOG.md
            git commit -m "docs(changelog): add ${{ inputs.tag }}"
            git push
          fi
