name: Release on tag

on:
  push:
    tags:
      - 'v*'   # se déclenche sur v2.0.73, v2.0.74, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # nécessaire pour créer/mettre à jour la Release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build Player
        run: |
          if [ -f package.json ]; then npm run build || npm run build:web || echo "no build"; fi

      - name: Prepare artifacts
        run: |
          mkdir -p out
          if [ -d ".next" ]; then zip -r out/player-${GITHUB_REF_NAME#v}.zip .next; \
          elif [ -d "dist" ]; then zip -r out/player-${GITHUB_REF_NAME#v}.zip dist; \
          elif [ -d "build" ]; then zip -r out/player-${GITHUB_REF_NAME#v}.zip build; \
          else echo "No build dir found (.next/dist/build)"; fi

      - name: Pick release notes file
        id: notes
        run: |
          TAG="${GITHUB_REF_NAME}"
          NOTES="RELEASE_NOTES_${TAG}.md"
          if [ -f "$NOTES" ]; then
            echo "file=$NOTES" >> $GITHUB_OUTPUT
          else
            echo "file=" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: IO Beats Player ${{ github.ref_name }}
          body_path: ${{ steps.notes.outputs.file }}
          files: |
            out/player-${{ github.ref_name#v }}.zip
