name: Release on tag (build + release + changelog)

on:
  push:
    tags:
      - 'v*'   # déclenché sur v2.0.73, v2.0.74, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # nécessaire pour créer/mettre à jour la Release ET pousser le changelog

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build Player
        run: |
          if [ -f package.json ]; then
            npm run build || npm run build:web || echo "no build"
          fi

      # tag = vX.Y.Z  |  version = X.Y.Z
      - name: Compute tag & version
        id: meta
        run: |
          echo "tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Prepare artifacts
        run: |
          mkdir -p out
          if [ -d ".next" ]; then
            zip -r "out/player-${{ steps.meta.outputs.version }}.zip" .next
          elif [ -d "dist" ]; then
            zip -r "out/player-${{ steps.meta.outputs.version }}.zip" dist
          elif [ -d "build" ]; then
            zip -r "out/player-${{ steps.meta.outputs.version }}.zip" build
          else
            echo "No build dir found (.next/dist/build)"
          fi

      - name: Pick release notes file
        id: notes
        run: |
          NOTES="RELEASE_NOTES_${GITHUB_REF_NAME}.md"
          if [ -f "$NOTES" ]; then
            echo "file=$NOTES" >> $GITHUB_OUTPUT
          else
            echo "file=" >> $GITHUB_OUTPUT
          fi

      # ===== Create GitHub Release =====
      - name: Create GitHub Release (with notes)
        if: steps.notes.outputs.file != ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          name: IO Beats Player ${{ steps.meta.outputs.tag }}
          body_path: ${{ steps.notes.outputs.file }}
          files: |
            out/player-${{ steps.meta.outputs.version }}.zip

      - name: Create GitHub Release (no notes)
        if: steps.notes.outputs.file == ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          name: IO Beats Player ${{ steps.meta.outputs.tag }}
          files: |
            out/player-${{ steps.meta.outputs.version }}.zip

      # ===== Update CHANGELOG.md =====
      - name: Update CHANGELOG.md from release notes (or skeleton)
        env:
          TAG: ${{ steps.meta.outputs.tag }}  # <-- passe vX.Y.Z à ton script
        run: node scripts/update-changelog.mjs

      - name: Commit & push changelog (if changed)
        run: |
          if git diff --quiet -- CHANGELOG.md; then
            echo "No changes in CHANGELOG.md"
          else
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add CHANGELOG.md
            git commit -m "docs(changelog): add ${{ steps.meta.outputs.tag }}"
            git push
          fi
